# Generated by Django 4.0 on 2022-01-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TodoList_text', models.CharField(max_length=200)),
                ('TodoList_content', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date updated')),
            ],
        ),
    ]
