# Generated by Django 4.0 on 2022-01-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='TodoList_checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
