# Generated by Django 3.2.8 on 2022-01-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TodoList_text', models.CharField(max_length=200)),
                ('TodoList_content', models.TextField()),
                ('TodoList_when', models.DateTimeField(verbose_name='target time')),
                ('TodoList_bool', models.BooleanField(default=False)),
            ],
        ),
    ]
