# Generated by Django 3.2.8 on 2022-01-04 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todolist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='TodoList_when',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='target time'),
        ),
    ]
