# Generated by Django 3.2.8 on 2022-01-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_alter_todolist_todolist_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='TodoList_where',
            field=models.TextField(blank=True),
        ),
    ]
